# Properties file for local/dev enviroment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/frescos.db
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8082