# Properties file for local/dev enviroment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

#spring:
#  datasource:
#    url: jdbc:mysql://proxysql.master.meliseginf.com:6612/g6frescos?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
#    username: ${LOCAL_DB_USER}
#    password: ${LOCAL_DB_PASS}
#  jpa:
#    show-sql: false
#    hibernate:
#    ddl-auto: none

spring:
  datasource:
    host: proxysql.master.meliseginf.com:6612
    db: g6frescos
    username: g6frescos_RPROD
    password: DB_MYSQL_DESAENV04_G6FRESCOS_G6FRESCOS_RPROD
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      sql: debug
      ddl-auto: create # create-drop para crear las entidades, una vez creadas y finalizado el mododel cambiar a none
    database-platform: org.hibernate.dialect.MySQL8Dialect (edited)