# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties

spring:
  datasource:
    host: DB_MYSQL_DESAENV04_MELIFG6DB_MELIFG6DB_ENDPOINT
    db: melifg6db
    username: melifg6db_WPROD
    password: DB_MYSQL_DESAENV04_MELIFG6DB_MELIFG6DB_WPROD
    initialization-mode: always
  jpa:
    show-sql: false
    hibernate:
      sql: debug
      ddl-auto: none # create-drop para crear las entidades, una vez creadas y finalizado el mododel cambiar a none
    database-platform: org.hibernate.dialect.MySQL8Dialect