# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties

spring:
  datasource:
    host: DB_MYSQL_DESAENV04_G6FRESCOS_G6FRESCOS_ENDPOINT
    db: g6frescos
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASS}
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      sql: debug
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect